### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Lzzzzzt** [LitttleHeroZZZX/hdu-jianlou#7]
```
Traceback (most recent call last):
  File "~/hdu-jianlou/demo.py", line 502, in <module>
    ex.login_course_selection()
  File "~/hdu-jianlou/demo.py", line 163, in login_course_selection
    link = link["onclick"].split("\'")
TypeError: 'NoneType' object is not subscriptable
```
按照README做的，但是报错

**Comment by LitttleHeroZZZX** [comment]
是不是没有在教务系统修改过密码？请先登录教务系统修改密码http://newjw.hdu.edu.cn/

**Comment by Lzzzzzt** [comment]
ok了，谢谢
